### ISSUE TITLE
Passing a variable into the perframe handler is unnecessary

### ISSUE THREAD

**Issue by dixon13** [SpyderBlack723/Spyder-Ambiance#1]
Why pass the the variable '_debug' into the per-frame handler if you are not going to use it?
```sqf
}, _delay, [_debug]] call CBA_fnc_addPerFrameHandler;
````
[Reference this] (https://github.com/SpyderBlack723/Spyder-Ambiance/blob/master/SpyderAmbiance/loopCheck.sqf#L95)

**Comment by SpyderBlack723** [comment]
This script has been completely abandoned. If I redo it, it won't contain any code from this. _debug was a remnant of a test that I forgot to remove. 

The entire things needs rewritten because I wrote it before I really knew what I was doing.

**Comment by SpyderBlack723** [comment]
Fixed: d1a5bc1

Unless there are any other easy fixes, I'm done with the script version and will focus mainly on the the modular version now included in SpyderAddons
https://github.com/SpyderBlack723/SpyderAddons/tree/develop/addons/amb_ambiance
